console.log("Assignment No 3");
var a="Sweety";
var b="Cutie";
console.log("value before swapping");
console.log("a=",a);
console.log("a=",b);
var temp_string;
var  temp_string=a;
var a=b;
var b=temp_string;
console.log("value after swapping");
console.log("a=",a);
console.log("a=",b);
console.log(".............................................");
var num1=100;
var num2=200;
var num3=300;
console.log("value before swapping");
console.log("num1=",num1);
console.log("num2=",num2);
console.log("num3=",num3);
var temp_num;
temp_num=num1;
num1=num2;
num2=num3;
num3=temp_num;
console.log("value after swapping");
console.log("num1=",num1);
console.log("num2=",num2);
console.log("num3=",num3);